Update Changelog.yaml

diff --git a/.github/workflows/Changelog.yaml b/.github/workflows/Changelog.yaml
--- a/.github/workflows/Changelog.yaml
+++ b/.github/workflows/Changelog.yaml
@@ -29,37 +29,50 @@ jobs:
     - uses: actions/checkout@v3
       with:
         fetch-depth: 0
-    - name: Validate Links
+    - name: Set up Python
+      uses: actions/setup-python@v2
+      with:
+        python-version: 3.8
+
+    - name: Install dependencies
       run: |
-        echo "Validating links in .md files"
-        md_files=$(find . -name "*.md")
-        pass_validation=true
-        # Loop through each Markdown file
-        for file in $md_files; do
-          # Extract and validate links
-          line_number=0
-          while IFS= read -r line; do
-            ((line_number++))
-            link=$(echo "$line" | grep -oP 'https:\/\/[^\s)\]]*')
-            if [ -n "$link" ]; then
-              # Validate the link using curl
-              http_code=$(curl -s -o /dev/null -I -w "%{http_code}" "$link")
-              if [[ "$http_code" != "200" ]] && [[ "$http_code" != "000" ]] && [[ "$http_code" != "302" ]]; then
-                echo "HTTP Status Code at line $line_number: $http_code"
-                echo "[ERROR] Invalid link in file: $file in line $line_number"
-                echo "The Line: $line"
-                pass_validation=false
-              elif [[ "$url" =~ "cla-assistant.io/" ]] && [[  "$url" != "https://cla-assistant.io/coralogix/$GITHUB_REPOSITORY" ]];then
-               echo "[INFO] Make sure that the CLA link is current" 
-              fi
-            fi
-          done < "$file"
-          done || true  # Continue even if there is an errors
-          # echo ">> All links are valid"
-          if [ "$pass_validation" == false ]; then
-            exit 1
-          fi
-      shell: bash
+        pip install mdformat mdlinkcheck
+
+    - name: Check documentation formatting and links
+      run: |
+        find . -regex ".*\.md" | xargs python3 -m mdformat --check
+        find . -regex ".*\.md" | xargs python3 -m mdlinkcheck
+    # - name: Validate Links
+    #   run: |
+    #     echo "Validating links in .md files"
+    #     md_files=$(find . -name "*.md")
+    #     pass_validation=true
+    #     # Loop through each Markdown file
+    #     for file in $md_files; do
+    #       # Extract and validate links
+    #       line_number=0
+    #       while IFS= read -r line; do
+    #         ((line_number++))
+    #         link=$(echo "$line" | grep -oP 'https:\/\/[^\s)\]]*')
+    #         if [ -n "$link" ]; then
+    #           # Validate the link using curl
+    #           http_code=$(curl -s -o /dev/null -I -w "%{http_code}" "$link")
+    #           if [[ "$http_code" != "200" ]] && [[ "$http_code" != "000" ]] && [[ "$http_code" != "302" ]]; then
+    #             echo "HTTP Status Code at line $line_number: $http_code"
+    #             echo "[ERROR] Invalid link in file: $file in line $line_number"
+    #             echo "The Line: $line"
+    #             pass_validation=false
+    #           elif [[ "$url" =~ "cla-assistant.io/" ]] && [[  "$url" != "https://cla-assistant.io/coralogix/$GITHUB_REPOSITORY" ]];then
+    #            echo "[INFO] Make sure that the CLA link is current" 
+    #           fi
+    #         fi
+    #       done < "$file"
+    #       done || true  # Continue even if there is an errors
+    #       # echo ">> All links are valid"
+    #       if [ "$pass_validation" == false ]; then
+    #         exit 1
+    #       fi
+    #   shell: bash
     # - name: Import environment variables from file
     #   run: cat ".github/env" >> $GITHUB_ENV
     # - uses: actions/setup-go@v4
