Update Changelog.yaml

diff --git a/.github/workflows/Changelog.yaml b/.github/workflows/Changelog.yaml
--- a/.github/workflows/Changelog.yaml
+++ b/.github/workflows/Changelog.yaml
@@ -29,18 +29,42 @@ jobs:
     - uses: actions/checkout@v3
       with:
         fetch-depth: 0
-    - name: Import environment variables from file
-      run: cat ".github/env" >> $GITHUB_ENV
-    - uses: actions/setup-go@v4
-      with:
-        go-version: '${{ env.golang-version }}'
-    - uses: actions/cache@v3
-      with:
-        path: .mdoxcache
-        key: mdoxcache
-    - name: ls
-      run: ls -a
-    - run: make check-docs
+    - name: validate
+      run: |
+        echo ">> Validating links in Markdown files"
+        # Find all Markdown files
+        md_files=$(find . -name "*.md")
+        
+        # Loop through each Markdown file
+        for file in $md_files; do
+          # Extract and validate links
+          while IFS= read -r line; do
+            link=$(echo "$line" | grep -oP '\[.*?\]\(\K.*?(?=\))')
+            if [ -n "$link" ]; then
+              # Validate the link using curl
+              curl -s -o /dev/null -I -w "%{http_code}" "$link"
+              status_code=$?
+              if [ $status_code -ne 200 ]; then
+                echo "Invalid link in file: $file"
+                echo "  $line"
+              fi
+            fi
+          done < "$file"
+        done
+    # - name: Import environment variables from file
+    #   run: cat ".github/env" >> $GITHUB_ENV
+    # - uses: actions/setup-go@v4
+    #   with:
+    #     go-version: '${{ env.golang-version }}'
+    # - uses: actions/cache@v3
+    #   with:
+    #     path: .mdoxcache
+    #     key: mdoxcache
+    # - name: ls
+    #   run: ls -a
+    # - run: make check-docs
+
+    
   check-changelog-updates:
     if: "${{ needs.get-label.outputs.labels != ' skip-changelog ' }}"
     runs-on: ubuntu-latest
