Update Changelog.yaml

diff --git a/.github/workflows/Changelog.yaml b/.github/workflows/Changelog.yaml
--- a/.github/workflows/Changelog.yaml
+++ b/.github/workflows/Changelog.yaml
@@ -33,6 +33,7 @@ jobs:
       run: |
         echo "Validating links in .md files"
         md_files=$(find . -name "*.md")
+        
         # Loop through each Markdown file
         for file in $md_files; do
           # Extract and validate links
@@ -42,8 +43,8 @@ jobs:
             link=$(echo "$line" | grep -oP 'https:\/\/[^[:space:]]*')
             if [ -n "$link" ]; then
               # Validate the link using curl
-              http_code=$(curl -s -o /dev/null -I -w "%{http_code}" "$link")
-              if [ $http_code -ne 200 ] ; then
+              http_code=$(curl -s -o /dev/null -I -w "%{http_code}" "$link" || echo "error")
+              if [ "$http_code" != "200" ] ; then
                 echo "HTTP Status Code at line $line_number: $http_code"
                 echo "Invalid link in file: $file"
                 echo "  $line"
@@ -51,7 +52,7 @@ jobs:
             fi
           done < "$file"
         done || true  # Continue even if there is an error
-        echo ">> All links are valid"
+echo ">> All links are valid"
       shell: bash
     # - name: Import environment variables from file
     #   run: cat ".github/env" >> $GITHUB_ENV
