Update tests.yaml

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -22,9 +22,10 @@ jobs:
         # validate the template file 
       - name: Run cfn-lint
         run: |
-          cfn-lint --template template.yaml --ignore-checks W  2> cfn-lint-error.log || true
-          if [ -s "cfn-lint-error.log" ]; then
-            echo "[INFO] no syntx error in the template"
+          cfn-lint --template template.yaml --ignore-checks W > cfn-lint-error.log 2>&1
+          cfn_lint_exit_code=$?
+          if [ $cfn_lint_exit_code -eq 0 ]; then
+            echo "[INFO] no syntax error in the template"
           else
             echo "[ERROR] please fix the template file"
             cat cfn-lint-error.log
