Update tests.yaml

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -22,13 +22,21 @@ jobs:
         # validate the template file 
       - name: Run cfn-lint
         run: |
-          cfn-lint --template template.yaml --ignore-checks W > cfn-lint-error.log 2>&1
-          cfn_lint_exit_code=$?
-          if [ $cfn_lint_exit_code -eq 0 ]; then
+          # cfn-lint --template template.yaml --ignore-checks W > cfn-lint-error.log 2>&1
+          # cfn_lint_exit_code=$?
+          # if [ $cfn_lint_exit_code -eq 0 ]; then
+          #   echo "[INFO] no syntax error in the template"
+          # else
+          #   echo "[ERROR] please fix the template file"
+          #   cat cfn-lint-error.log
+          #   exit 1
+          # fi
+          error=$(cfn-lint --template template.yaml --region us-east-1 --ignore-checks W)
+          if [ $error == "" ]; then
             echo "[INFO] no syntax error in the template"
           else
             echo "[ERROR] please fix the template file"
-            cat cfn-lint-error.log
+            echo $error
             exit 1
           fi
       
