Update tests.yaml

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -21,7 +21,15 @@ jobs:
   
       - name: Run cfn-lint
         run: |
-          cfn-lint --template template.yaml --ignore-checks W
+          cfn-lint --template template.yaml --ignore-checks W 2> cfn-lint-error.log || true
+          
+      - name: Display cfn-lint errors
+        run: |
+          if [[ cat cfn-lint-error.log == "" ]];then
+            echo "no error"
+          else
+            echo "error"
+          fi
       
       # - name: install rust toolchain
       #   uses: actions-rs/toolchain@v1
